Traceback (most recent call last):
  File "/Users/tsauter/venv/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
T0 = 288
dt = 60*60*24*365
T = step_forward(341.3, T0, Cw, 0.32, 0.57, dt)
print('New equlibrium emperature {:.2f} after 1 year'.format(T))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/tt/q4k5594x1tz82j1yrmtkdw080000gn/T/ipykernel_8526/4112886546.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mT0[0m [0;34m=[0m [0;36m288[0m[0;34m[0m[0m
[1;32m      2[0m [0mdt[0m [0;34m=[0m [0;36m60[0m[0;34m*[0m[0;36m60[0m[0;34m*[0m[0;36m24[0m[0;34m*[0m[0;36m365[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mT[0m [0;34m=[0m [0mstep_forward[0m[0;34m([0m[0;36m341.3[0m[0;34m,[0m [0mT0[0m[0;34m,[0m [0mCw[0m[0;34m,[0m [0;36m0.32[0m[0;34m,[0m [0;36m0.57[0m[0;34m,[0m [0mdt[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mprint[0m[0;34m([0m[0;34m'New equlibrium emperature {:.2f} after 1 year'[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mT[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'Cw' is not defined
NameError: name 'Cw' is not defined

